config/routes.rb
Rails.application.routes.draw do
  get 'search', to: "search#index"
  root "articles#index"

  resources :articles do
    resources :comments

    resource :image, only: [:destroy]

  end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  include Visible

  has_many :comments, dependent: :destroy
  has_one_attached :image
  # has_rich_text :image_body

  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 10 }

  def self.ransackable_attributes(auth_object = nil)
    ["title"]
  end

  def self.ransackable_associations(auth_object = nil)
   []
  end

  def image_as_thumbnail
    return unless image.content_type.in?(%w[image/jpeg image/png image/jpg])
    image.variant(resize_to_limit: [270, 270]).processed
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  include Visible

  belongs_to :article
end

app/models/concerns/visible.rb
module Visible
  extend ActiveSupport::Concern

  VALID_STATUSES = ['public', 'private', 'archived']

  included do
    validates :status, inclusion: { in: VALID_STATUSES }
  end

  class_methods do
    def public_count
      where(status: 'public').count
    end
  end

  def archived?
    status == 'archived'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_query

  def set_query
    @query = Article.ransack(params[:q])
  end

  def index
    # @articles = Article.all
    @query = Article.ransack(params[:q])
    @articles = @query.result(distinct: true)
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to root_path, status: :see_other
  end

  private
    def article_params
      params.require(:article).permit(:title, :body, :status, :image)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article), status: :see_other
  end

  private
    def comment_params
      params.require(:comment).permit(:commenter, :body, :status)
    end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_article

  def destroy
    @article.image.purge_later
    redirect_to edit_article_path(@article)
  end

  private
  def set_article
    @article = Article.find(params[:article_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/articles/_form.html.erb
<%= form_with model: article do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% article.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %><br>
    <% article.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :status %><br>
    <%= form.select :status, Visible::VALID_STATUSES, selected: article.status || 'public' %>
  </div>

  

  <%# if @article.image.content_type.in?(%w[image/jpeg image/png image/jpg]) %>
<!--  <div class="position-relative">-->
    <%#= image_tag(@article.image_as_thumbnail, style: "margin-right: 10px;") if @article.image.attached?%>
    <%#= link_to "Remove Image", article_image_path(@article), data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, type: "button", class: "btn btn-danger  position-absolute top-0" %>
<!--  </div>-->
  <%# end %>
<!---->
<!--  <div>-->
    <%#= form.label :image %>
    <%#= form.file_field :image %>
<!--  </div>-->
  
  <%= render 'image_preview', form: form, article: @article %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/_image_preview.html.erb
<div data-controller="previews">
        <div class="position-relative">
            
            <% if article.image.attached? %>
                <%= image_tag article.image, data: { previews_target: "preview" }, style: "width: 270px; height: auto; margin-right: 10px;" %>
                <%= link_to "Remove Image", article_image_path(@article), data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, type: "button", class: "btn btn-danger position-absolute top-0" %>
            <% else %>
                <%= image_tag "", data: { previews_target: "preview" }, style: "width: 270px; height: auto; margin-right: 10px;"%>
                <%= button_tag "Remover Imagem", id: 'remove_image_button', type: 'button',  data: { action: "click->previews#remove"}, class: "btn btn-danger position-absolute top-0", style:"display: none;" %>
            <% end %>
        </div>

    <%= form.label :image %>
    <%= form.file_field :image,
        id: "image_upload",
        direct_upload: true, 
        data: { previews_target: "input", action: "change->previews#preview"} %>
    
</div>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render "form", article: @article %>

app/views/articles/index.html.erb
<div class="container">
  <h1>Articles</h1>

  <div id="articles">
    <%= link_to "New Article", new_article_path, class: "btn btn-success", role: "button" %>

    <br>
    <br>
    Our blog has <%= Article.public_count %> articles and counting!
    <br>
    <br>
    <div class="row row-cols-1 row-cols-md-4 g-4">
      <% @articles.each do |article| %>
        <div class="col">
          <div class="card" style="height: 25rem;">
            <div class="card-body"> 
              <h5 class="card-title"><%= article.title %></h5>
              <p class="card-subtitle mb-3"><small class="text-muted">Last updated <%= article.updated_at %></small></p>
              <p class="card-text"><%= article.body %></p>
            </div>
            <div class="card-footer">
                <%= link_to "Read more>", article %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= form_with model: @article do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% @article.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %><br>
    <% @article.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/show.html.erb
<div class="container">
  <br>
  <% if @article.image.content_type.in?(%w[image/jpeg image/png image/jpg]) %>
    <%= image_tag(@article.image_as_thumbnail) if @article.image.attached?%>
  <% end %>

  <h1><%= @article.title %></h1>
  <small class="text-muted">Last updated <%= @article.updated_at %></small></p>
  
  <p><%= @article.body %></p>
</div>

<div class="container">
  <br>
  <div class="row row-cols-auto">
    <div class="col">
      <%= link_to "Edit", edit_article_path(@article), class: "btn btn-secondary" %>
    </div>
    <div class="col">  
      <%= link_to "Destroy",
          article_path(@article), 
          data: {
              turbo_method: :delete,
              turbo_confirm: "Are you sure?"
          },
          class: "btn btn-danger" 
      %>
    </div>
    <div class="col">
      <%= link_to "Back to articles", articles_path, class: "btn btn-primary" %>
    </div>
  </div>
  <br>
</div>

<div class="container">
  <h2>Comments</h2>
  <%= render @article.comments %>

  <h2>Add a comment:</h2>
  <%= render 'comments/form' %>
</div>

app/views/comments/_comment.html.erb
<% unless comment.archived? %>
  <p>
    <strong>Commenter:</strong>
    <%= comment.commenter %>
  </p>

  <p>
    <strong>Comment:</strong>
    <%= comment.body %>
  </p>

  <p>
    <%= link_to "Destroy Comment", [comment.article, comment], data: {
                  turbo_method: :delete,
                  turbo_confirm: "Are you sure?"
                } %>
  </p>
<% end %>

app/views/comments/_form.html.erb
<%= form_with model: [ @article, @article.comments.build ] do |form| %>
  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.label :status %><br>
    <%= form.select :status, Visible::VALID_STATUSES, selected: 'public' %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body style="height: 100%; background-color: #F5F5F5;">
    <%= render "shared/header" %>
      <div class="container">
        <div class="row">
          <%= yield %>
        </div>
      </div>
  </body>
</html>
<!--#F5F5F5-->

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary" style="background-color: #DCDCDC;">
  <div class="container-fluid">
    <a class="navbar-brand" href=<%= root_path %> style="color: #808080;">Blog</a>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Home', root_path, class: "nav-link active", 'aria-current' => "page", style: 'color: #696969;' %>
        </li>
      </ul>
      <%= search_form_for @query, url: articles_path, class: "d-flex", role: "search" do |f| %>
        <%= f.search_field :title_cont, class: "form-control me-2", type: "search", placeholder: "Search" %>
        <%= f.button class: "btn btn-outline-success", type: "submit" do %>
          <i class="bi bi-search"></i>
        <% end %>
      <% end %>
      
    </div>
  </div>
</nav>